### PR TITLE
Add support for clearing file issues in the Delphi IDE

### PR DESCRIPTION
**Pull request by fourls**
This PR adds a new "Clear Active File" menu option to the Delphi IDE, which (as the name suggests) clears all issues from the active file.

This has required a number of refactors, particularly around ensuring that issue objects can be relied upon to persist after their analysis has been deleted.

### CODE REVIEW

**Review by Cirras — CHANGES_REQUESTED** [review]
Looks like you may have accidentally flipped `DelphiLint.Plugin` to utf-8 (without bom) which will be interpreted as ansi by the compiler.
image

**Comment by Cirras** [comment]
Same thing in `DelphiLint.ToolFrame`.
image

**Comment by Cirras** [comment]
Looks like both files were flipped to utf-8 in c215b2a67b4b665724314b20938cbf29be76f980 and then flipped back to ansi in 370fa948bcd299548ecf05fdbcf054f79444a18b.

**Comment by fourls** [comment]
Huh... how weird. I'll fix that up.

**Pull request merged**
